server:
  port: 8080
springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    version: openapi_3_1
springdoc-bridge:
  protobuf:
    schema-naming-strategy: protobuf